export const ADMIN = 'ADMIN_ROLE';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_USERS = 'GET_USERS';
export const UPDATE_USER = 'UPDATE_USER';

export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_THEME = 'CHANGE_THEME';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const ADD_PRODUCT_SHOPPING_CART = 'ADD_PRODUCT_SHOPPING_CART';
export const REMOVE_PRODUCT_SHOPPING_CART = 'REMOVE_PRODUCT_SHOPPING_CART';
export const INCREASE_PRODUCT_SHOPPING_CART = 'INCREASE_PRODUCT_SHOPPING_CART';
export const DECREASE_PRODUCT_SHOPPING_CART = 'DECREASE_PRODUCT_SHOPPING_CART';